---
title: "Convert PCAWG"
author: "Chela James"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PCAWG conversion

This is the conversion of the R object created by Jhouseham with the PCAWG drivers from hg19 coordinates to hg38 coordinates
Initially I will do the conversion. We may need to check if they match the mutations

get liftover file 
wget https://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz

I have taken only those variants with a position

```{r load_objects}
library(rtracklayer)
library(tidyverse)
chainFile <- "hg19ToHg38.over.chain"
chain <- import.chain(chainFile)
load('PCAWG_TabS3_drivers.rda')

# get rid of non numeric position
my_df <- PCAWG_TabS3_drivers %>%
  select(chr, pos, ref, alt, gene) %>%
  filter(!str_detect(pos, "x"))

# make a granges object for liftOver function from rtracklayer
gr <- GRanges(
  seqnames = Rle(my_df$chr),
  ranges = IRanges(start = as.numeric(my_df$pos), end = as.numeric(my_df$pos)),
  ref = my_df$ref,
  alt = my_df$alt,
  gene = my_df$gene
)

# run liftOver
my_gr <- liftOver(gr, chain = chain)
# return to dataframe
my_gr_df <- as.data.frame(my_gr) %>%
            select(seqnames,start,ref,alt,gene) %>%
            rename(chr = seqnames, pos = start)

saveRDS(my_gr_df,"PCAWG_hg38_liftover.rds")

```

